import matplotlib.pyplot as plt
import numpy

coronaWorld = {
    "Global": {
        "NewConfirmed": 192654,
        "TotalConfirmed": 11373773,
        "NewDeaths": 5645,
        "TotalDeaths": 539471,
        "NewRecovered": 195718,
        "TotalRecovered": 6058914
    },
    "Countries": [
        {
            "Country": "Afghanistan",
            "CountryCode": "AF",
            "Slug": "afghanistan",
            "NewConfirmed": 348,
            "TotalConfirmed": 32672,
            "NewDeaths": 7,
            "TotalDeaths": 826,
            "NewRecovered": 1833,
            "TotalRecovered": 19164,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Albania",
            "CountryCode": "AL",
            "Slug": "albania",
            "NewConfirmed": 67,
            "TotalConfirmed": 2819,
            "NewDeaths": 2,
            "TotalDeaths": 74,
            "NewRecovered": 45,
            "TotalRecovered": 1637,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Algeria",
            "CountryCode": "DZ",
            "Slug": "algeria",
            "NewConfirmed": 430,
            "TotalConfirmed": 15500,
            "NewDeaths": 9,
            "TotalDeaths": 946,
            "NewRecovered": 349,
            "TotalRecovered": 11181,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Andorra",
            "CountryCode": "AD",
            "Slug": "andorra",
            "NewConfirmed": 0,
            "TotalConfirmed": 855,
            "NewDeaths": 0,
            "TotalDeaths": 52,
            "NewRecovered": 0,
            "TotalRecovered": 800,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Angola",
            "CountryCode": "AO",
            "Slug": "angola",
            "NewConfirmed": 18,
            "TotalConfirmed": 346,
            "NewDeaths": 1,
            "TotalDeaths": 19,
            "NewRecovered": 1,
            "TotalRecovered": 108,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Antigua and Barbuda",
            "CountryCode": "AG",
            "Slug": "antigua-and-barbuda",
            "NewConfirmed": 0,
            "TotalConfirmed": 68,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 23,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Argentina",
            "CountryCode": "AR",
            "Slug": "argentina",
            "NewConfirmed": 2590,
            "TotalConfirmed": 75376,
            "NewDeaths": 44,
            "TotalDeaths": 1481,
            "NewRecovered": 706,
            "TotalRecovered": 25930,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Armenia",
            "CountryCode": "AM",
            "Slug": "armenia",
            "NewConfirmed": 580,
            "TotalConfirmed": 27900,
            "NewDeaths": 8,
            "TotalDeaths": 477,
            "NewRecovered": 451,
            "TotalRecovered": 15935,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Australia",
            "CountryCode": "AU",
            "Slug": "australia",
            "NewConfirmed": 183,
            "TotalConfirmed": 8443,
            "NewDeaths": 0,
            "TotalDeaths": 104,
            "NewRecovered": 80,
            "TotalRecovered": 7399,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Austria",
            "CountryCode": "AT",
            "Slug": "austria",
            "NewConfirmed": 115,
            "TotalConfirmed": 18165,
            "NewDeaths": 0,
            "TotalDeaths": 705,
            "NewRecovered": 49,
            "TotalRecovered": 16607,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Azerbaijan",
            "CountryCode": "AZ",
            "Slug": "azerbaijan",
            "NewConfirmed": 534,
            "TotalConfirmed": 19801,
            "NewDeaths": 6,
            "TotalDeaths": 241,
            "NewRecovered": 471,
            "TotalRecovered": 11291,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bahamas",
            "CountryCode": "BS",
            "Slug": "bahamas",
            "NewConfirmed": 0,
            "TotalConfirmed": 104,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 0,
            "TotalRecovered": 89,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bahrain",
            "CountryCode": "BH",
            "Slug": "bahrain",
            "NewConfirmed": 447,
            "TotalConfirmed": 28857,
            "NewDeaths": 1,
            "TotalDeaths": 96,
            "NewRecovered": 641,
            "TotalRecovered": 23959,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bangladesh",
            "CountryCode": "BD",
            "Slug": "bangladesh",
            "NewConfirmed": 3288,
            "TotalConfirmed": 159679,
            "NewDeaths": 29,
            "TotalDeaths": 1997,
            "NewRecovered": 2673,
            "TotalRecovered": 70721,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Barbados",
            "CountryCode": "BB",
            "Slug": "barbados",
            "NewConfirmed": 0,
            "TotalConfirmed": 97,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 0,
            "TotalRecovered": 90,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Belarus",
            "CountryCode": "BY",
            "Slug": "belarus",
            "NewConfirmed": 273,
            "TotalConfirmed": 63270,
            "NewDeaths": 6,
            "TotalDeaths": 418,
            "NewRecovered": 760,
            "TotalRecovered": 50669,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Belgium",
            "CountryCode": "BE",
            "Slug": "belgium",
            "NewConfirmed": 111,
            "TotalConfirmed": 61838,
            "NewDeaths": 6,
            "TotalDeaths": 9771,
            "NewRecovered": 18,
            "TotalRecovered": 17091,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Belize",
            "CountryCode": "BZ",
            "Slug": "belize",
            "NewConfirmed": 0,
            "TotalConfirmed": 30,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 19,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Benin",
            "CountryCode": "BJ",
            "Slug": "benin",
            "NewConfirmed": 0,
            "TotalConfirmed": 1199,
            "NewDeaths": 0,
            "TotalDeaths": 21,
            "NewRecovered": 0,
            "TotalRecovered": 333,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bhutan",
            "CountryCode": "BT",
            "Slug": "bhutan",
            "NewConfirmed": 1,
            "TotalConfirmed": 78,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 1,
            "TotalRecovered": 51,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bolivia",
            "CountryCode": "BO",
            "Slug": "bolivia",
            "NewConfirmed": 1253,
            "TotalConfirmed": 38071,
            "NewDeaths": 58,
            "TotalDeaths": 1378,
            "NewRecovered": 506,
            "TotalRecovered": 11272,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bosnia and Herzegovina",
            "CountryCode": "BA",
            "Slug": "bosnia-and-herzegovina",
            "NewConfirmed": 0,
            "TotalConfirmed": 4962,
            "NewDeaths": 0,
            "TotalDeaths": 191,
            "NewRecovered": 0,
            "TotalRecovered": 2550,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Botswana",
            "CountryCode": "BW",
            "Slug": "botswana",
            "NewConfirmed": 0,
            "TotalConfirmed": 277,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 29,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Brazil",
            "CountryCode": "BR",
            "Slug": "brazil",
            "NewConfirmed": 37923,
            "TotalConfirmed": 1577004,
            "NewDeaths": 2381,
            "TotalDeaths": 64265,
            "NewRecovered": 6116,
            "TotalRecovered": 990731,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Brunei Darussalam",
            "CountryCode": "BN",
            "Slug": "brunei",
            "NewConfirmed": 0,
            "TotalConfirmed": 141,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 138,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Bulgaria",
            "CountryCode": "BG",
            "Slug": "bulgaria",
            "NewConfirmed": 180,
            "TotalConfirmed": 5677,
            "NewDeaths": 2,
            "TotalDeaths": 241,
            "NewRecovered": 6,
            "TotalRecovered": 2898,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Burkina Faso",
            "CountryCode": "BF",
            "Slug": "burkina-faso",
            "NewConfirmed": 7,
            "TotalConfirmed": 987,
            "NewDeaths": 0,
            "TotalDeaths": 53,
            "NewRecovered": 2,
            "TotalRecovered": 854,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Burundi",
            "CountryCode": "BI",
            "Slug": "burundi",
            "NewConfirmed": 0,
            "TotalConfirmed": 191,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 118,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Cambodia",
            "CountryCode": "KH",
            "Slug": "cambodia",
            "NewConfirmed": 0,
            "TotalConfirmed": 141,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 131,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Cameroon",
            "CountryCode": "CM",
            "Slug": "cameroon",
            "NewConfirmed": 0,
            "TotalConfirmed": 12592,
            "NewDeaths": 0,
            "TotalDeaths": 313,
            "NewRecovered": 0,
            "TotalRecovered": 10100,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Canada",
            "CountryCode": "CA",
            "Slug": "canada",
            "NewConfirmed": 446,
            "TotalConfirmed": 214370,
            "NewDeaths": 20,
            "TotalDeaths": 17462,
            "NewRecovered": 275,
            "TotalRecovered": 70507,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Cape Verde",
            "CountryCode": "CV",
            "Slug": "cape-verde",
            "NewConfirmed": 39,
            "TotalConfirmed": 1421,
            "NewDeaths": 1,
            "TotalDeaths": 16,
            "NewRecovered": 25,
            "TotalRecovered": 654,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Central African Republic",
            "CountryCode": "CF",
            "Slug": "central-african-republic",
            "NewConfirmed": 51,
            "TotalConfirmed": 3969,
            "NewDeaths": 0,
            "TotalDeaths": 48,
            "NewRecovered": 55,
            "TotalRecovered": 914,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Chad",
            "CountryCode": "TD",
            "Slug": "chad",
            "NewConfirmed": 0,
            "TotalConfirmed": 871,
            "NewDeaths": 0,
            "TotalDeaths": 74,
            "NewRecovered": 1,
            "TotalRecovered": 787,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Chile",
            "CountryCode": "CL",
            "Slug": "chile",
            "NewConfirmed": 3758,
            "TotalConfirmed": 291847,
            "NewDeaths": 141,
            "TotalDeaths": 6192,
            "NewRecovered": 4108,
            "TotalRecovered": 257451,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "China",
            "CountryCode": "CN",
            "Slug": "china",
            "NewConfirmed": 19,
            "TotalConfirmed": 84857,
            "NewDeaths": 0,
            "TotalDeaths": 4641,
            "NewRecovered": 26,
            "TotalRecovered": 79706,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Colombia",
            "CountryCode": "CO",
            "Slug": "colombia",
            "NewConfirmed": 3401,
            "TotalConfirmed": 109793,
            "NewDeaths": 150,
            "TotalDeaths": 4001,
            "NewRecovered": 803,
            "TotalRecovered": 45409,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Comoros",
            "CountryCode": "KM",
            "Slug": "comoros",
            "NewConfirmed": 0,
            "TotalConfirmed": 309,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 0,
            "TotalRecovered": 241,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Congo (Brazzaville)",
            "CountryCode": "CG",
            "Slug": "congo-brazzaville",
            "NewConfirmed": 0,
            "TotalConfirmed": 1557,
            "NewDeaths": 0,
            "TotalDeaths": 44,
            "NewRecovered": 0,
            "TotalRecovered": 501,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Congo (Kinshasa)",
            "CountryCode": "CD",
            "Slug": "congo-kinshasa",
            "NewConfirmed": 68,
            "TotalConfirmed": 7379,
            "NewDeaths": 3,
            "TotalDeaths": 182,
            "NewRecovered": 277,
            "TotalRecovered": 2961,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Costa Rica",
            "CountryCode": "CR",
            "Slug": "costa-rica",
            "NewConfirmed": 310,
            "TotalConfirmed": 4621,
            "NewDeaths": 0,
            "TotalDeaths": 18,
            "NewRecovered": 64,
            "TotalRecovered": 1721,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Croatia",
            "CountryCode": "HR",
            "Slug": "croatia",
            "NewConfirmed": 86,
            "TotalConfirmed": 3094,
            "NewDeaths": 1,
            "TotalDeaths": 113,
            "NewRecovered": 15,
            "TotalRecovered": 2183,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Cuba",
            "CountryCode": "CU",
            "Slug": "cuba",
            "NewConfirmed": 8,
            "TotalConfirmed": 2369,
            "NewDeaths": 0,
            "TotalDeaths": 86,
            "NewRecovered": 3,
            "TotalRecovered": 2227,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Cyprus",
            "CountryCode": "CY",
            "Slug": "cyprus",
            "NewConfirmed": 3,
            "TotalConfirmed": 1002,
            "NewDeaths": 0,
            "TotalDeaths": 19,
            "NewRecovered": 0,
            "TotalRecovered": 839,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Czech Republic",
            "CountryCode": "CZ",
            "Slug": "czech-republic",
            "NewConfirmed": 121,
            "TotalConfirmed": 12440,
            "NewDeaths": 0,
            "TotalDeaths": 353,
            "NewRecovered": 4,
            "TotalRecovered": 7852,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Côte d'Ivoire",
            "CountryCode": "CI",
            "Slug": "cote-divoire",
            "NewConfirmed": 218,
            "TotalConfirmed": 10462,
            "NewDeaths": 2,
            "TotalDeaths": 72,
            "NewRecovered": 81,
            "TotalRecovered": 4807,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Denmark",
            "CountryCode": "DK",
            "Slug": "denmark",
            "NewConfirmed": 0,
            "TotalConfirmed": 13032,
            "NewDeaths": 0,
            "TotalDeaths": 606,
            "NewRecovered": 0,
            "TotalRecovered": 12017,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Djibouti",
            "CountryCode": "DJ",
            "Slug": "djibouti",
            "NewConfirmed": 0,
            "TotalConfirmed": 4736,
            "NewDeaths": 0,
            "TotalDeaths": 55,
            "NewRecovered": 0,
            "TotalRecovered": 4580,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Dominica",
            "CountryCode": "DM",
            "Slug": "dominica",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 18,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Dominican Republic",
            "CountryCode": "DO",
            "Slug": "dominican-republic",
            "NewConfirmed": 1036,
            "TotalConfirmed": 36184,
            "NewDeaths": 11,
            "TotalDeaths": 786,
            "NewRecovered": 210,
            "TotalRecovered": 18602,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Ecuador",
            "CountryCode": "EC",
            "Slug": "ecuador",
            "NewConfirmed": 878,
            "TotalConfirmed": 61535,
            "NewDeaths": 69,
            "TotalDeaths": 4769,
            "NewRecovered": 116,
            "TotalRecovered": 28507,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Egypt",
            "CountryCode": "EG",
            "Slug": "egypt",
            "NewConfirmed": 1324,
            "TotalConfirmed": 74035,
            "NewDeaths": 79,
            "TotalDeaths": 3280,
            "NewRecovered": 413,
            "TotalRecovered": 20103,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "El Salvador",
            "CountryCode": "SV",
            "Slug": "el-salvador",
            "NewConfirmed": 240,
            "TotalConfirmed": 7507,
            "NewDeaths": 8,
            "TotalDeaths": 210,
            "NewRecovered": 166,
            "TotalRecovered": 4434,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Equatorial Guinea",
            "CountryCode": "GQ",
            "Slug": "equatorial-guinea",
            "NewConfirmed": 0,
            "TotalConfirmed": 3071,
            "NewDeaths": 0,
            "TotalDeaths": 51,
            "NewRecovered": 0,
            "TotalRecovered": 842,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Eritrea",
            "CountryCode": "ER",
            "Slug": "eritrea",
            "NewConfirmed": 0,
            "TotalConfirmed": 215,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 56,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Estonia",
            "CountryCode": "EE",
            "Slug": "estonia",
            "NewConfirmed": 2,
            "TotalConfirmed": 1993,
            "NewDeaths": 0,
            "TotalDeaths": 69,
            "NewRecovered": 11,
            "TotalRecovered": 1870,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Ethiopia",
            "CountryCode": "ET",
            "Slug": "ethiopia",
            "NewConfirmed": 0,
            "TotalConfirmed": 5846,
            "NewDeaths": 0,
            "TotalDeaths": 103,
            "NewRecovered": 0,
            "TotalRecovered": 2430,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Fiji",
            "CountryCode": "FJ",
            "Slug": "fiji",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 18,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Finland",
            "CountryCode": "FI",
            "Slug": "finland",
            "NewConfirmed": 6,
            "TotalConfirmed": 7248,
            "NewDeaths": 0,
            "TotalDeaths": 329,
            "NewRecovered": 0,
            "TotalRecovered": 6700,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "France",
            "CountryCode": "FR",
            "Slug": "france",
            "NewConfirmed": 0,
            "TotalConfirmed": 204222,
            "NewDeaths": 0,
            "TotalDeaths": 29896,
            "NewRecovered": 0,
            "TotalRecovered": 77185,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Gabon",
            "CountryCode": "GA",
            "Slug": "gabon",
            "NewConfirmed": 0,
            "TotalConfirmed": 5620,
            "NewDeaths": 0,
            "TotalDeaths": 44,
            "NewRecovered": 0,
            "TotalRecovered": 2555,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Gambia",
            "CountryCode": "GM",
            "Slug": "gambia",
            "NewConfirmed": 2,
            "TotalConfirmed": 57,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 27,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Georgia",
            "CountryCode": "GE",
            "Slug": "georgia",
            "NewConfirmed": 5,
            "TotalConfirmed": 948,
            "NewDeaths": 0,
            "TotalDeaths": 15,
            "NewRecovered": 4,
            "TotalRecovered": 825,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Germany",
            "CountryCode": "DE",
            "Slug": "germany",
            "NewConfirmed": 418,
            "TotalConfirmed": 197198,
            "NewDeaths": 10,
            "TotalDeaths": 9020,
            "NewRecovered": 700,
            "TotalRecovered": 181000,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Ghana",
            "CountryCode": "GH",
            "Slug": "ghana",
            "NewConfirmed": 0,
            "TotalConfirmed": 19388,
            "NewDeaths": 0,
            "TotalDeaths": 117,
            "NewRecovered": 0,
            "TotalRecovered": 14330,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Greece",
            "CountryCode": "GR",
            "Slug": "greece",
            "NewConfirmed": 25,
            "TotalConfirmed": 3511,
            "NewDeaths": 0,
            "TotalDeaths": 192,
            "NewRecovered": 0,
            "TotalRecovered": 1374,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Grenada",
            "CountryCode": "GD",
            "Slug": "grenada",
            "NewConfirmed": 0,
            "TotalConfirmed": 23,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 23,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Guatemala",
            "CountryCode": "GT",
            "Slug": "guatemala",
            "NewConfirmed": 1208,
            "TotalConfirmed": 22501,
            "NewDeaths": 40,
            "TotalDeaths": 920,
            "NewRecovered": 15,
            "TotalRecovered": 3330,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Guinea",
            "CountryCode": "GN",
            "Slug": "guinea",
            "NewConfirmed": 49,
            "TotalConfirmed": 5570,
            "NewDeaths": 1,
            "TotalDeaths": 34,
            "NewRecovered": 50,
            "TotalRecovered": 4496,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Guinea-Bissau",
            "CountryCode": "GW",
            "Slug": "guinea-bissau",
            "NewConfirmed": 0,
            "TotalConfirmed": 1765,
            "NewDeaths": 0,
            "TotalDeaths": 25,
            "NewRecovered": 0,
            "TotalRecovered": 676,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Guyana",
            "CountryCode": "GY",
            "Slug": "guyana",
            "NewConfirmed": 16,
            "TotalConfirmed": 272,
            "NewDeaths": 0,
            "TotalDeaths": 14,
            "NewRecovered": 3,
            "TotalRecovered": 120,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Haiti",
            "CountryCode": "HT",
            "Slug": "haiti",
            "NewConfirmed": 64,
            "TotalConfirmed": 6294,
            "NewDeaths": 3,
            "TotalDeaths": 113,
            "NewRecovered": 122,
            "TotalRecovered": 1408,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Holy See (Vatican City State)",
            "CountryCode": "VA",
            "Slug": "holy-see-vatican-city-state",
            "NewConfirmed": 0,
            "TotalConfirmed": 12,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 12,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Honduras",
            "CountryCode": "HN",
            "Slug": "honduras",
            "NewConfirmed": 805,
            "TotalConfirmed": 22921,
            "NewDeaths": 24,
            "TotalDeaths": 629,
            "NewRecovered": 137,
            "TotalRecovered": 2387,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Hungary",
            "CountryCode": "HU",
            "Slug": "hungary",
            "NewConfirmed": 2,
            "TotalConfirmed": 4174,
            "NewDeaths": 1,
            "TotalDeaths": 589,
            "NewRecovered": 32,
            "TotalRecovered": 2784,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Iceland",
            "CountryCode": "IS",
            "Slug": "iceland",
            "NewConfirmed": 5,
            "TotalConfirmed": 1860,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 1,
            "TotalRecovered": 1833,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "India",
            "CountryCode": "IN",
            "Slug": "india",
            "NewConfirmed": 24850,
            "TotalConfirmed": 673165,
            "NewDeaths": 613,
            "TotalDeaths": 19268,
            "NewRecovered": 14856,
            "TotalRecovered": 409083,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Indonesia",
            "CountryCode": "ID",
            "Slug": "indonesia",
            "NewConfirmed": 1447,
            "TotalConfirmed": 62142,
            "NewDeaths": 53,
            "TotalDeaths": 3089,
            "NewRecovered": 651,
            "TotalRecovered": 28219,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Iran, Islamic Republic of",
            "CountryCode": "IR",
            "Slug": "iran",
            "NewConfirmed": 2449,
            "TotalConfirmed": 237878,
            "NewDeaths": 148,
            "TotalDeaths": 11408,
            "NewRecovered": 2503,
            "TotalRecovered": 198949,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Iraq",
            "CountryCode": "IQ",
            "Slug": "iraq",
            "NewConfirmed": 2334,
            "TotalConfirmed": 58354,
            "NewDeaths": 106,
            "TotalDeaths": 2368,
            "NewRecovered": 1477,
            "TotalRecovered": 31077,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Ireland",
            "CountryCode": "IE",
            "Slug": "ireland",
            "NewConfirmed": 11,
            "TotalConfirmed": 25509,
            "NewDeaths": 1,
            "TotalDeaths": 1741,
            "NewRecovered": 0,
            "TotalRecovered": 23364,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Israel",
            "CountryCode": "IL",
            "Slug": "israel",
            "NewConfirmed": 1115,
            "TotalConfirmed": 29170,
            "NewDeaths": 4,
            "TotalDeaths": 330,
            "NewRecovered": 147,
            "TotalRecovered": 17816,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Italy",
            "CountryCode": "IT",
            "Slug": "italy",
            "NewConfirmed": 235,
            "TotalConfirmed": 241419,
            "NewDeaths": 21,
            "TotalDeaths": 34854,
            "NewRecovered": 477,
            "TotalRecovered": 191944,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Jamaica",
            "CountryCode": "JM",
            "Slug": "jamaica",
            "NewConfirmed": 7,
            "TotalConfirmed": 728,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 4,
            "TotalRecovered": 569,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Japan",
            "CountryCode": "JP",
            "Slug": "japan",
            "NewConfirmed": 276,
            "TotalConfirmed": 19461,
            "NewDeaths": 0,
            "TotalDeaths": 977,
            "NewRecovered": 111,
            "TotalRecovered": 16832,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Jordan",
            "CountryCode": "JO",
            "Slug": "jordan",
            "NewConfirmed": 3,
            "TotalConfirmed": 1150,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 5,
            "TotalRecovered": 902,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Kazakhstan",
            "CountryCode": "KZ",
            "Slug": "kazakhstan",
            "NewConfirmed": 1452,
            "TotalConfirmed": 47171,
            "NewDeaths": 0,
            "TotalDeaths": 188,
            "NewRecovered": 280,
            "TotalRecovered": 15556,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Kenya",
            "CountryCode": "KE",
            "Slug": "kenya",
            "NewConfirmed": 389,
            "TotalConfirmed": 7577,
            "NewDeaths": 5,
            "TotalDeaths": 159,
            "NewRecovered": 88,
            "TotalRecovered": 2236,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Korea (South)",
            "CountryCode": "KR",
            "Slug": "korea-south",
            "NewConfirmed": 61,
            "TotalConfirmed": 13091,
            "NewDeaths": 0,
            "TotalDeaths": 283,
            "NewRecovered": 21,
            "TotalRecovered": 11832,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Kuwait",
            "CountryCode": "KW",
            "Slug": "kuwait",
            "NewConfirmed": 631,
            "TotalConfirmed": 49303,
            "NewDeaths": 5,
            "TotalDeaths": 365,
            "NewRecovered": 667,
            "TotalRecovered": 39943,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Kyrgyzstan",
            "CountryCode": "KG",
            "Slug": "kyrgyzstan",
            "NewConfirmed": 216,
            "TotalConfirmed": 7094,
            "NewDeaths": 2,
            "TotalDeaths": 78,
            "NewRecovered": 43,
            "TotalRecovered": 2714,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Lao PDR",
            "CountryCode": "LA",
            "Slug": "lao-pdr",
            "NewConfirmed": 0,
            "TotalConfirmed": 19,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 19,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Latvia",
            "CountryCode": "LV",
            "Slug": "latvia",
            "NewConfirmed": 1,
            "TotalConfirmed": 1123,
            "NewDeaths": 0,
            "TotalDeaths": 30,
            "NewRecovered": 3,
            "TotalRecovered": 1000,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Lebanon",
            "CountryCode": "LB",
            "Slug": "lebanon",
            "NewConfirmed": 25,
            "TotalConfirmed": 1855,
            "NewDeaths": 0,
            "TotalDeaths": 35,
            "NewRecovered": 12,
            "TotalRecovered": 1304,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Lesotho",
            "CountryCode": "LS",
            "Slug": "lesotho",
            "NewConfirmed": 0,
            "TotalConfirmed": 35,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 11,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Liberia",
            "CountryCode": "LR",
            "Slug": "liberia",
            "NewConfirmed": 36,
            "TotalConfirmed": 869,
            "NewDeaths": 0,
            "TotalDeaths": 37,
            "NewRecovered": 23,
            "TotalRecovered": 369,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Libya",
            "CountryCode": "LY",
            "Slug": "libya",
            "NewConfirmed": 71,
            "TotalConfirmed": 989,
            "NewDeaths": 0,
            "TotalDeaths": 27,
            "NewRecovered": 28,
            "TotalRecovered": 258,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Liechtenstein",
            "CountryCode": "LI",
            "Slug": "liechtenstein",
            "NewConfirmed": 0,
            "TotalConfirmed": 83,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 81,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Lithuania",
            "CountryCode": "LT",
            "Slug": "lithuania",
            "NewConfirmed": 3,
            "TotalConfirmed": 1831,
            "NewDeaths": 0,
            "TotalDeaths": 79,
            "NewRecovered": 6,
            "TotalRecovered": 1545,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Luxembourg",
            "CountryCode": "LU",
            "Slug": "luxembourg",
            "NewConfirmed": 29,
            "TotalConfirmed": 4476,
            "NewDeaths": 0,
            "TotalDeaths": 110,
            "NewRecovered": 0,
            "TotalRecovered": 4016,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Macedonia, Republic of",
            "CountryCode": "MK",
            "Slug": "macedonia",
            "NewConfirmed": 145,
            "TotalConfirmed": 6932,
            "NewDeaths": 6,
            "TotalDeaths": 334,
            "NewRecovered": 111,
            "TotalRecovered": 2987,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Madagascar",
            "CountryCode": "MG",
            "Slug": "madagascar",
            "NewConfirmed": 216,
            "TotalConfirmed": 2728,
            "NewDeaths": 3,
            "TotalDeaths": 29,
            "NewRecovered": 21,
            "TotalRecovered": 1078,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Malawi",
            "CountryCode": "MW",
            "Slug": "malawi",
            "NewConfirmed": 115,
            "TotalConfirmed": 1613,
            "NewDeaths": 1,
            "TotalDeaths": 17,
            "NewRecovered": 0,
            "TotalRecovered": 317,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Malaysia",
            "CountryCode": "MY",
            "Slug": "malaysia",
            "NewConfirmed": 10,
            "TotalConfirmed": 8658,
            "NewDeaths": 0,
            "TotalDeaths": 121,
            "NewRecovered": 15,
            "TotalRecovered": 8461,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Maldives",
            "CountryCode": "MV",
            "Slug": "maldives",
            "NewConfirmed": 25,
            "TotalConfirmed": 2435,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 1976,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Mali",
            "CountryCode": "ML",
            "Slug": "mali",
            "NewConfirmed": 18,
            "TotalConfirmed": 2303,
            "NewDeaths": 1,
            "TotalDeaths": 118,
            "NewRecovered": 9,
            "TotalRecovered": 1516,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Malta",
            "CountryCode": "MT",
            "Slug": "malta",
            "NewConfirmed": 0,
            "TotalConfirmed": 672,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 1,
            "TotalRecovered": 651,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Mauritania",
            "CountryCode": "MR",
            "Slug": "mauritania",
            "NewConfirmed": 122,
            "TotalConfirmed": 4827,
            "NewDeaths": 0,
            "TotalDeaths": 129,
            "NewRecovered": 40,
            "TotalRecovered": 1805,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Mauritius",
            "CountryCode": "MU",
            "Slug": "mauritius",
            "NewConfirmed": 0,
            "TotalConfirmed": 341,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 330,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Mexico",
            "CountryCode": "MX",
            "Slug": "mexico",
            "NewConfirmed": 6914,
            "TotalConfirmed": 252165,
            "NewDeaths": 523,
            "TotalDeaths": 30366,
            "NewRecovered": 6379,
            "TotalRecovered": 195724,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Moldova",
            "CountryCode": "MD",
            "Slug": "moldova",
            "NewConfirmed": 227,
            "TotalConfirmed": 17672,
            "NewDeaths": 8,
            "TotalDeaths": 580,
            "NewRecovered": 303,
            "TotalRecovered": 10396,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Monaco",
            "CountryCode": "MC",
            "Slug": "monaco",
            "NewConfirmed": 0,
            "TotalConfirmed": 106,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 95,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Mongolia",
            "CountryCode": "MN",
            "Slug": "mongolia",
            "NewConfirmed": 0,
            "TotalConfirmed": 220,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 2,
            "TotalRecovered": 185,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Montenegro",
            "CountryCode": "ME",
            "Slug": "montenegro",
            "NewConfirmed": 57,
            "TotalConfirmed": 720,
            "NewDeaths": 1,
            "TotalDeaths": 14,
            "NewRecovered": 0,
            "TotalRecovered": 315,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Morocco",
            "CountryCode": "MA",
            "Slug": "morocco",
            "NewConfirmed": 534,
            "TotalConfirmed": 13822,
            "NewDeaths": 2,
            "TotalDeaths": 232,
            "NewRecovered": 169,
            "TotalRecovered": 9329,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Mozambique",
            "CountryCode": "MZ",
            "Slug": "mozambique",
            "NewConfirmed": 30,
            "TotalConfirmed": 969,
            "NewDeaths": 1,
            "TotalDeaths": 7,
            "NewRecovered": 7,
            "TotalRecovered": 256,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Myanmar",
            "CountryCode": "MM",
            "Slug": "myanmar",
            "NewConfirmed": 7,
            "TotalConfirmed": 313,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 3,
            "TotalRecovered": 240,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Namibia",
            "CountryCode": "NA",
            "Slug": "namibia",
            "NewConfirmed": 25,
            "TotalConfirmed": 375,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 25,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Nepal",
            "CountryCode": "NP",
            "Slug": "nepal",
            "NewConfirmed": 232,
            "TotalConfirmed": 15491,
            "NewDeaths": 2,
            "TotalDeaths": 34,
            "NewRecovered": 272,
            "TotalRecovered": 6415,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Netherlands",
            "CountryCode": "NL",
            "Slug": "netherlands",
            "NewConfirmed": 2,
            "TotalConfirmed": 50548,
            "NewDeaths": 0,
            "TotalDeaths": 6132,
            "NewRecovered": 1,
            "TotalRecovered": 187,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "New Zealand",
            "CountryCode": "NZ",
            "Slug": "new-zealand",
            "NewConfirmed": 3,
            "TotalConfirmed": 1533,
            "NewDeaths": 0,
            "TotalDeaths": 22,
            "NewRecovered": 0,
            "TotalRecovered": 1490,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Nicaragua",
            "CountryCode": "NI",
            "Slug": "nicaragua",
            "NewConfirmed": 0,
            "TotalConfirmed": 2519,
            "NewDeaths": 0,
            "TotalDeaths": 83,
            "NewRecovered": 0,
            "TotalRecovered": 1238,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Niger",
            "CountryCode": "NE",
            "Slug": "niger",
            "NewConfirmed": 0,
            "TotalConfirmed": 1082,
            "NewDeaths": 0,
            "TotalDeaths": 68,
            "NewRecovered": 0,
            "TotalRecovered": 963,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Nigeria",
            "CountryCode": "NG",
            "Slug": "nigeria",
            "NewConfirmed": 603,
            "TotalConfirmed": 28167,
            "NewDeaths": 6,
            "TotalDeaths": 634,
            "NewRecovered": 393,
            "TotalRecovered": 11462,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Norway",
            "CountryCode": "NO",
            "Slug": "norway",
            "NewConfirmed": 5,
            "TotalConfirmed": 8926,
            "NewDeaths": 0,
            "TotalDeaths": 251,
            "NewRecovered": 0,
            "TotalRecovered": 8138,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Oman",
            "CountryCode": "OM",
            "Slug": "oman",
            "NewConfirmed": 1177,
            "TotalConfirmed": 45106,
            "NewDeaths": 10,
            "TotalDeaths": 203,
            "NewRecovered": 799,
            "TotalRecovered": 26968,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Pakistan",
            "CountryCode": "PK",
            "Slug": "pakistan",
            "NewConfirmed": 3387,
            "TotalConfirmed": 225283,
            "NewDeaths": 68,
            "TotalDeaths": 4619,
            "NewRecovered": 11471,
            "TotalRecovered": 125094,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Palestinian Territory",
            "CountryCode": "PS",
            "Slug": "palestine",
            "NewConfirmed": 501,
            "TotalConfirmed": 3835,
            "NewDeaths": 2,
            "TotalDeaths": 13,
            "NewRecovered": 0,
            "TotalRecovered": 463,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Panama",
            "CountryCode": "PA",
            "Slug": "panama",
            "NewConfirmed": 988,
            "TotalConfirmed": 36983,
            "NewDeaths": 22,
            "TotalDeaths": 720,
            "NewRecovered": 816,
            "TotalRecovered": 17761,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Papua New Guinea",
            "CountryCode": "PG",
            "Slug": "papua-new-guinea",
            "NewConfirmed": 0,
            "TotalConfirmed": 11,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 8,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Paraguay",
            "CountryCode": "PY",
            "Slug": "paraguay",
            "NewConfirmed": 36,
            "TotalConfirmed": 2385,
            "NewDeaths": 1,
            "TotalDeaths": 20,
            "NewRecovered": 21,
            "TotalRecovered": 1134,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Peru",
            "CountryCode": "PE",
            "Slug": "peru",
            "NewConfirmed": 3481,
            "TotalConfirmed": 299080,
            "NewDeaths": 186,
            "TotalDeaths": 10412,
            "NewRecovered": 3769,
            "TotalRecovered": 189621,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Philippines",
            "CountryCode": "PH",
            "Slug": "philippines",
            "NewConfirmed": 1494,
            "TotalConfirmed": 41830,
            "NewDeaths": 10,
            "TotalDeaths": 1290,
            "NewRecovered": 380,
            "TotalRecovered": 11453,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Poland",
            "CountryCode": "PL",
            "Slug": "poland",
            "NewConfirmed": 314,
            "TotalConfirmed": 35719,
            "NewDeaths": 5,
            "TotalDeaths": 1512,
            "NewRecovered": 476,
            "TotalRecovered": 23127,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Portugal",
            "CountryCode": "PT",
            "Slug": "portugal",
            "NewConfirmed": 413,
            "TotalConfirmed": 43569,
            "NewDeaths": 7,
            "TotalDeaths": 1605,
            "NewRecovered": 348,
            "TotalRecovered": 28772,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Qatar",
            "CountryCode": "QA",
            "Slug": "qatar",
            "NewConfirmed": 530,
            "TotalConfirmed": 99183,
            "NewDeaths": 2,
            "TotalDeaths": 123,
            "NewRecovered": 1804,
            "TotalRecovered": 90387,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Republic of Kosovo",
            "CountryCode": "XK",
            "Slug": "kosovo",
            "NewConfirmed": 0,
            "TotalConfirmed": 3064,
            "NewDeaths": 0,
            "TotalDeaths": 55,
            "NewRecovered": 0,
            "TotalRecovered": 1707,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Romania",
            "CountryCode": "RO",
            "Slug": "romania",
            "NewConfirmed": 416,
            "TotalConfirmed": 28582,
            "NewDeaths": 23,
            "TotalDeaths": 1731,
            "NewRecovered": 309,
            "TotalRecovered": 19854,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Russian Federation",
            "CountryCode": "RU",
            "Slug": "russia",
            "NewConfirmed": 6623,
            "TotalConfirmed": 673564,
            "NewDeaths": 167,
            "TotalDeaths": 10011,
            "NewRecovered": 8972,
            "TotalRecovered": 446127,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Rwanda",
            "CountryCode": "RW",
            "Slug": "rwanda",
            "NewConfirmed": 11,
            "TotalConfirmed": 1092,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 11,
            "TotalRecovered": 523,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Saint Kitts and Nevis",
            "CountryCode": "KN",
            "Slug": "saint-kitts-and-nevis",
            "NewConfirmed": 1,
            "TotalConfirmed": 16,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 15,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Saint Lucia",
            "CountryCode": "LC",
            "Slug": "saint-lucia",
            "NewConfirmed": 0,
            "TotalConfirmed": 22,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 19,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Saint Vincent and Grenadines",
            "CountryCode": "VC",
            "Slug": "saint-vincent-and-the-grenadines",
            "NewConfirmed": 0,
            "TotalConfirmed": 29,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 29,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "San Marino",
            "CountryCode": "SM",
            "Slug": "san-marino",
            "NewConfirmed": 0,
            "TotalConfirmed": 698,
            "NewDeaths": 0,
            "TotalDeaths": 42,
            "NewRecovered": 0,
            "TotalRecovered": 656,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Sao Tome and Principe",
            "CountryCode": "ST",
            "Slug": "sao-tome-and-principe",
            "NewConfirmed": 0,
            "TotalConfirmed": 719,
            "NewDeaths": 0,
            "TotalDeaths": 13,
            "NewRecovered": 0,
            "TotalRecovered": 267,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Saudi Arabia",
            "CountryCode": "SA",
            "Slug": "saudi-arabia",
            "NewConfirmed": 4128,
            "TotalConfirmed": 205929,
            "NewDeaths": 56,
            "TotalDeaths": 1858,
            "NewRecovered": 2642,
            "TotalRecovered": 143256,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Senegal",
            "CountryCode": "SN",
            "Slug": "senegal",
            "NewConfirmed": 108,
            "TotalConfirmed": 7272,
            "NewDeaths": 4,
            "TotalDeaths": 129,
            "NewRecovered": 47,
            "TotalRecovered": 4713,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Serbia",
            "CountryCode": "RS",
            "Slug": "serbia",
            "NewConfirmed": 325,
            "TotalConfirmed": 15829,
            "NewDeaths": 8,
            "TotalDeaths": 306,
            "NewRecovered": 112,
            "TotalRecovered": 13176,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Seychelles",
            "CountryCode": "SC",
            "Slug": "seychelles",
            "NewConfirmed": 0,
            "TotalConfirmed": 81,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 11,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Sierra Leone",
            "CountryCode": "SL",
            "Slug": "sierra-leone",
            "NewConfirmed": 9,
            "TotalConfirmed": 1533,
            "NewDeaths": 0,
            "TotalDeaths": 62,
            "NewRecovered": 9,
            "TotalRecovered": 1051,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Singapore",
            "CountryCode": "SG",
            "Slug": "singapore",
            "NewConfirmed": 185,
            "TotalConfirmed": 44664,
            "NewDeaths": 0,
            "TotalDeaths": 26,
            "NewRecovered": 348,
            "TotalRecovered": 40117,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Slovakia",
            "CountryCode": "SK",
            "Slug": "slovakia",
            "NewConfirmed": 29,
            "TotalConfirmed": 1749,
            "NewDeaths": 0,
            "TotalDeaths": 28,
            "NewRecovered": 0,
            "TotalRecovered": 1466,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Slovenia",
            "CountryCode": "SI",
            "Slug": "slovenia",
            "NewConfirmed": 29,
            "TotalConfirmed": 1679,
            "NewDeaths": 0,
            "TotalDeaths": 111,
            "NewRecovered": 0,
            "TotalRecovered": 1384,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Somalia",
            "CountryCode": "SO",
            "Slug": "somalia",
            "NewConfirmed": 17,
            "TotalConfirmed": 2961,
            "NewDeaths": 2,
            "TotalDeaths": 92,
            "NewRecovered": 22,
            "TotalRecovered": 973,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "South Africa",
            "CountryCode": "ZA",
            "Slug": "south-africa",
            "NewConfirmed": 10853,
            "TotalConfirmed": 187977,
            "NewDeaths": 74,
            "TotalDeaths": 3026,
            "NewRecovered": 4929,
            "TotalRecovered": 91227,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "South Sudan",
            "CountryCode": "SS",
            "Slug": "south-sudan",
            "NewConfirmed": 0,
            "TotalConfirmed": 2021,
            "NewDeaths": 0,
            "TotalDeaths": 38,
            "NewRecovered": 0,
            "TotalRecovered": 333,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Spain",
            "CountryCode": "ES",
            "Slug": "spain",
            "NewConfirmed": 0,
            "TotalConfirmed": 250545,
            "NewDeaths": 0,
            "TotalDeaths": 28385,
            "NewRecovered": 0,
            "TotalRecovered": 150376,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Sri Lanka",
            "CountryCode": "LK",
            "Slug": "sri-lanka",
            "NewConfirmed": 5,
            "TotalConfirmed": 2074,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 22,
            "TotalRecovered": 1885,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Sudan",
            "CountryCode": "SD",
            "Slug": "sudan",
            "NewConfirmed": 104,
            "TotalConfirmed": 9767,
            "NewDeaths": 4,
            "TotalDeaths": 608,
            "NewRecovered": 49,
            "TotalRecovered": 4673,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Suriname",
            "CountryCode": "SR",
            "Slug": "suriname",
            "NewConfirmed": 4,
            "TotalConfirmed": 565,
            "NewDeaths": 1,
            "TotalDeaths": 14,
            "NewRecovered": 9,
            "TotalRecovered": 276,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Swaziland",
            "CountryCode": "SZ",
            "Slug": "swaziland",
            "NewConfirmed": 45,
            "TotalConfirmed": 954,
            "NewDeaths": 0,
            "TotalDeaths": 13,
            "NewRecovered": 20,
            "TotalRecovered": 535,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Sweden",
            "CountryCode": "SE",
            "Slug": "sweden",
            "NewConfirmed": 0,
            "TotalConfirmed": 71419,
            "NewDeaths": 0,
            "TotalDeaths": 5420,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Switzerland",
            "CountryCode": "CH",
            "Slug": "switzerland",
            "NewConfirmed": 97,
            "TotalConfirmed": 32198,
            "NewDeaths": 0,
            "TotalDeaths": 1965,
            "NewRecovered": 0,
            "TotalRecovered": 29200,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Syrian Arab Republic (Syria)",
            "CountryCode": "SY",
            "Slug": "syria",
            "NewConfirmed": 10,
            "TotalConfirmed": 338,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 123,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Taiwan, Republic of China",
            "CountryCode": "TW",
            "Slug": "taiwan",
            "NewConfirmed": 0,
            "TotalConfirmed": 449,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 0,
            "TotalRecovered": 438,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Tajikistan",
            "CountryCode": "TJ",
            "Slug": "tajikistan",
            "NewConfirmed": 101,
            "TotalConfirmed": 6159,
            "NewDeaths": 0,
            "TotalDeaths": 52,
            "NewRecovered": 119,
            "TotalRecovered": 4809,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Tanzania, United Republic of",
            "CountryCode": "TZ",
            "Slug": "tanzania",
            "NewConfirmed": 0,
            "TotalConfirmed": 509,
            "NewDeaths": 0,
            "TotalDeaths": 21,
            "NewRecovered": 0,
            "TotalRecovered": 183,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Thailand",
            "CountryCode": "TH",
            "Slug": "thailand",
            "NewConfirmed": 5,
            "TotalConfirmed": 3185,
            "NewDeaths": 0,
            "TotalDeaths": 58,
            "NewRecovered": 0,
            "TotalRecovered": 3066,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Timor-Leste",
            "CountryCode": "TL",
            "Slug": "timor-leste",
            "NewConfirmed": 0,
            "TotalConfirmed": 24,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 24,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Togo",
            "CountryCode": "TG",
            "Slug": "togo",
            "NewConfirmed": 5,
            "TotalConfirmed": 676,
            "NewDeaths": 1,
            "TotalDeaths": 15,
            "NewRecovered": 8,
            "TotalRecovered": 432,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Trinidad and Tobago",
            "CountryCode": "TT",
            "Slug": "trinidad-and-tobago",
            "NewConfirmed": 0,
            "TotalConfirmed": 130,
            "NewDeaths": 0,
            "TotalDeaths": 8,
            "NewRecovered": 0,
            "TotalRecovered": 115,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Tunisia",
            "CountryCode": "TN",
            "Slug": "tunisia",
            "NewConfirmed": 5,
            "TotalConfirmed": 1186,
            "NewDeaths": 0,
            "TotalDeaths": 50,
            "NewRecovered": 1,
            "TotalRecovered": 1046,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Turkey",
            "CountryCode": "TR",
            "Slug": "turkey",
            "NewConfirmed": 1154,
            "TotalConfirmed": 204610,
            "NewDeaths": 20,
            "TotalDeaths": 5206,
            "NewRecovered": 1214,
            "TotalRecovered": 179492,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Uganda",
            "CountryCode": "UG",
            "Slug": "uganda",
            "NewConfirmed": 16,
            "TotalConfirmed": 927,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 19,
            "TotalRecovered": 868,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Ukraine",
            "CountryCode": "UA",
            "Slug": "ukraine",
            "NewConfirmed": 923,
            "TotalConfirmed": 48628,
            "NewDeaths": 16,
            "TotalDeaths": 1243,
            "NewRecovered": 611,
            "TotalRecovered": 21907,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "United Arab Emirates",
            "CountryCode": "AE",
            "Slug": "united-arab-emirates",
            "NewConfirmed": 716,
            "TotalConfirmed": 50857,
            "NewDeaths": 3,
            "TotalDeaths": 321,
            "NewRecovered": 704,
            "TotalRecovered": 39857,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "United Kingdom",
            "CountryCode": "GB",
            "Slug": "united-kingdom",
            "NewConfirmed": 625,
            "TotalConfirmed": 286412,
            "NewDeaths": 67,
            "TotalDeaths": 44283,
            "NewRecovered": 0,
            "TotalRecovered": 1375,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "United States of America",
            "CountryCode": "US",
            "Slug": "united-states",
            "NewConfirmed": 45283,
            "TotalConfirmed": 2839436,
            "NewDeaths": 242,
            "TotalDeaths": 129676,
            "NewRecovered": 103921,
            "TotalRecovered": 894325,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Uruguay",
            "CountryCode": "UY",
            "Slug": "uruguay",
            "NewConfirmed": 3,
            "TotalConfirmed": 955,
            "NewDeaths": 0,
            "TotalDeaths": 28,
            "NewRecovered": 3,
            "TotalRecovered": 840,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Uzbekistan",
            "CountryCode": "UZ",
            "Slug": "uzbekistan",
            "NewConfirmed": 312,
            "TotalConfirmed": 9708,
            "NewDeaths": 2,
            "TotalDeaths": 31,
            "NewRecovered": 174,
            "TotalRecovered": 6425,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Venezuela (Bolivarian Republic)",
            "CountryCode": "VE",
            "Slug": "venezuela",
            "NewConfirmed": 213,
            "TotalConfirmed": 6750,
            "NewDeaths": 3,
            "TotalDeaths": 62,
            "NewRecovered": 0,
            "TotalRecovered": 2100,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Viet Nam",
            "CountryCode": "VN",
            "Slug": "vietnam",
            "NewConfirmed": 0,
            "TotalConfirmed": 355,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 340,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Western Sahara",
            "CountryCode": "EH",
            "Slug": "western-sahara",
            "NewConfirmed": 0,
            "TotalConfirmed": 10,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 8,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Yemen",
            "CountryCode": "YE",
            "Slug": "yemen",
            "NewConfirmed": 8,
            "TotalConfirmed": 1248,
            "NewDeaths": 2,
            "TotalDeaths": 337,
            "NewRecovered": 1,
            "TotalRecovered": 537,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Zambia",
            "CountryCode": "ZM",
            "Slug": "zambia",
            "NewConfirmed": 0,
            "TotalConfirmed": 1632,
            "NewDeaths": 0,
            "TotalDeaths": 30,
            "NewRecovered": 0,
            "TotalRecovered": 1348,
            "Date": "2020-07-05T06:10:11Z"
        },
        {
            "Country": "Zimbabwe",
            "CountryCode": "ZW",
            "Slug": "zimbabwe",
            "NewConfirmed": 73,
            "TotalConfirmed": 698,
            "NewDeaths": 1,
            "TotalDeaths": 8,
            "NewRecovered": 5,
            "TotalRecovered": 181,
            "Date": "2020-07-05T06:10:11Z"
        }
    ],
    "Date": "2020-07-05T06:10:11Z"
}

countries = coronaWorld["Countries"]
countriesList = [element["Country"] for element in countries if element["TotalConfirmed"] > 20000]
totalConfirmedList = [element["TotalConfirmed"] for element in countries if element["TotalConfirmed"] > 20000]
print(countriesList)
print(totalConfirmedList)

plt.bar(countriesList, totalConfirmedList)
for i in range(len(plt.xticks()[0])):
    plt.annotate(countriesList[i], (i-.05, totalConfirmedList[i]), rotation=90)
#plt.xticks(rotation=90)
plt.xticks(countriesList,"")
plt.show()